import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { POST_KEY, safePath } from "../filesystem/paths";
export async function generateRegistry(root = process.cwd()) {
  const content = path.join(root, "content");
  const keys: string[] = [];
  async function walk(relative: string, depth: number) {
    const directory = relative ? await safePath(content, relative) : content;
    for (const entry of await readdir(directory, { withFileTypes: true })) {
      if (!entry.isDirectory() || entry.isSymbolicLink()) continue;
      const next = relative ? `${relative}/${entry.name}` : entry.name;
      if (depth === 3) {
        if (!POST_KEY.test(next)) continue;
        try {
          await readFile(await safePath(content, `${next}/Post.tsx`));
          keys.push(next);
        } catch {
          /* reported by discovery */
        }
      } else await walk(next, depth + 1);
    }
  }
  await walk("", 0);
  keys.sort();
  const output = `// Generated by npm run registry. Do not edit.\n"use client";\nimport type { ComponentType } from "react";\nimport type { PostProps } from "@/types/post";\n${keys.map((k, i) => `import Post${i} from ${JSON.stringify(`../../content/${k}/Post`)};`).join("\n")}\nexport const postRegistry: Record<string, ComponentType<PostProps>> = {\n${keys.map((k, i) => `  ${JSON.stringify(k)}: Post${i},`).join("\n")}\n};\n`;
  const destination = path.join(root, "src/lib/content-registry.ts");
  let previous = "";
  try {
    previous = await readFile(destination, "utf8");
  } catch {}
  if (previous !== output) await writeFile(destination, output);
  return keys;
}
