// Generated by npm run registry. Do not edit.
"use client";
import type { ComponentType } from "react";
import type { PostProps } from "@/types/post";
import Post0 from "../../content/2026/09/week-03/example-post/Post";
export const postRegistry: Record<string, ComponentType<PostProps>> = {
  "2026/09/week-03/example-post": Post0,
};
