import type { ContentStyleTokens } from "../schema";
export const tokens = {
  colors: {
    canvas: "#f9f9f7",
    surface: "#eeeeea",
    ink: "#282a28",
    muted: "#646762",
    accent: "#484d45",
    line: "#c9cbc6",
    inverseCanvas: "#282a28",
    inverseInk: "#f9f9f7",
  },
  typography: {
    bodyFamily: "Arial, Helvetica, sans-serif",
    labelFamily: "Arial, Helvetica, sans-serif",
    sizes: {
      label: 18,
      small: 24,
      body: 30,
      storyBody: 34,
      title: 88,
      squareTitle: 70,
      storyTitle: 100,
    },
    titleWeight: 500,
    bodyWeight: 400,
    titleLineHeight: 1.05,
    bodyLineHeight: 1.5,
    titleTracking: -3,
    labelTracking: 2,
  },
  spacing: {
    unit: 4,
    small: 16,
    medium: 32,
    large: 48,
    gutter: 76,
    squareGutter: 64,
    storyGutter: 90,
    lead: 80,
    storyLead: 120,
    safe: 130,
  },
  sizing: {
    contentWidth: 900,
    bodyWidth: 720,
    graphicWidth: 440,
    graphicHeight: 400,
    icon: 64,
  },
  borders: { width: 1, style: "solid" },
  radii: { card: 0 },
  strokes: { width: 2 },
  layout: { columns: "1.5fr 1fr", imageTreatment: "contain" },
} satisfies ContentStyleTokens;
